services:
  web:
    extends:
      file: docker-compose.yml
      service: web
    image: blossomlabs/blobscan-web:${BLOBSCAN_WEB_TAG}
    ports:
      - ${EXTERNAL_WEB_PORT}:3000

  api:
    extends:
      file: docker-compose.yml
      service: api
    image: blossomlabs/blobscan-api:${BLOBSCAN_API_TAG}
    ports:
      - ${EXTERNAL_API_PORT}:3001

  indexer:
    extends:
      file: docker-compose.yml
      service: indexer
    image: blossomlabs/blobscan-indexer:${INDEXER_TAG}
