services:
  web:
    extends:
      file: docker-compose.yml
      service: web
    build:
      context: .
      target: web
    ports:
      - 5556:5556 # Prisma studio

  api:
    extends:
      file: docker-compose.yml
      service: api
    build:
      context: .
      target: api
    depends_on:
      - postgres

  docs:
    extends:
      file: docker-compose.yml
      service: docs
    build:
      context: .
      dockerfile: ./Dockerfile.docs

  # External dependencies

  postgres:
    image: postgres:16
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - /tmp:/tmp
      - ./docker-entrypoint-initdb.d/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    environment:
      - POSTGRES_USER=blobscan
      - POSTGRES_DB=blobscan_dev
      - POSTGRES_PASSWORD=s3cr3t
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U blobscan -d blobscan_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  storage:
    image: fsouza/fake-gcs-server
    ports:
      - "4443:4443"
    command: ["-scheme", "http", "-port", "4443", "-data", "/data"]
    volumes:
      - gcs_data:/data
      - type: bind
        source: ./packages/test/src/fixtures/gcs
        target: /data
  s3mock:
    image: adobe/s3mock:latest
    environment:
      - COM_ADOBE_TESTING_S3MOCK_STORE_INITIAL_BUCKETS=blobscan-s3-bucket
      - COM_ADOBE_TESTING_S3MOCK_STORE_REGION=us-east-1
    ports:
      - 9090:9090
  redis:
    image: "redis:alpine"
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    volumes:
      - ./misc/data:/var/lib/redis
      - ./misc/conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=s3cr3t
      - REDIS_USERNAME=blobscan

  collector:
    image: otel/opentelemetry-collector:0.23.0
    command: "--config /etc/otel-config.yaml"
    volumes:
      - ./otel-config.yaml:/etc/otel-config.yaml

  dagster-blobscan:
    build:
      context: ./apps/dagster
      dockerfile: ./Dockerfile
    restart: always
    environment:
      CHAIN_ID: "${CHAIN_ID}"
      DAGSTER_POSTGRES_USER: "blobscan"
      DAGSTER_POSTGRES_PASSWORD: "s3cr3t"
      DAGSTER_POSTGRES_DB: "dagster_dev"
      DAGSTER_POSTGRES_PORT: 5432
    volumes:
      - dagster-home:/dagster_home
    depends_on:
      - postgres

  dagster-webserver:
    build:
      context: ./apps/dagster
      dockerfile: ./Dockerfile.dagster
    entrypoint:
      - dagster-webserver
      - -h
      - "0.0.0.0"
      - -p
      - "3003"
      - -w
      - workspace.yaml
    container_name: dagster-webserver
    expose:
      - "3003"
    ports:
      - "3003:3003"
    environment:
      DAGSTER_POSTGRES_USER: "blobscan"
      DAGSTER_POSTGRES_PASSWORD: "s3cr3t"
      DAGSTER_POSTGRES_DB: "dagster_dev"
      DAGSTER_POSTGRES_PORT: 5432
    volumes: # Make docker client accessible so we can terminate containers from the webserver
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/io_manager_storage:/tmp/io_manager_storage
    depends_on:
      postgres:
        condition: service_healthy
      dagster-blobscan:
        condition: service_healthy

  dagster-daemon:
    build:
      context: ./apps/dagster
      dockerfile: ./Dockerfile.dagster
    entrypoint:
      - dagster-daemon
      - run
    container_name: dagster-daemon
    restart: on-failure
    environment:
      DAGSTER_POSTGRES_USER: "blobscan"
      DAGSTER_POSTGRES_PASSWORD: "s3cr3t"
      DAGSTER_POSTGRES_DB: "dagster_dev"
      DAGSTER_POSTGRES_PORT: 5432
    volumes: # Make docker client accessible so we can launch containers using host docker
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/io_manager_storage:/tmp/io_manager_storage
    depends_on:
      postgres:
        condition: service_healthy
      dagster-blobscan:
        condition: service_started

volumes:
  postgres-data:
  gcs_data:
  dagster-home:
