import dynamic from "next/dynamic";
import type { ComponentType, SVGProps } from "react";

import type { Rollup } from "~/types";
import type { RenderableIcon } from "~/types/icons";

type SvgComponent = ComponentType<SVGProps<SVGElement>>;
type RollupIconRegistry = { [key in Rollup]?: RenderableIcon };

const svg = (loader: () => Promise<{ default: SvgComponent }>) =>
  dynamic(loader);

export const ICONS: RollupIconRegistry = {
  abstract: svg(() => import("./abstract.svg")),
  aevo: svg(() => import("./aevo.svg")),
  ancient8: svg(() => import("./ancient8.svg")),
  arbitrum: svg(() => import("./arbitrum.svg")),
  arenaz: svg(() => import("./arenaz.svg")),
  base: svg(() => import("./base.svg")),
  blast: svg(() => import("./blast.svg")),
  bob: svg(() => import("./bob.svg")),
  boba: svg(() => import("./boba.svg")),
  camp: svg(() => import("./camp.svg")),
  codex: svg(() => import("./codex.svg")),
  debankchain: svg(() => import("./debank.svg")),
  ethernity: svg(() => import("./ethernity.svg")),
  flynet: svg(() => import("./flynet.svg")),
  fraxtal: svg(() => import("./fraxtal.svg")),
  fuel: svg(() => import("./fuel.svg")),
  gravity: svg(() => import("./gravity.svg")),
  hashkey: svg(() => import("./hashkey.svg")),
  hemi: svg(() => import("./hemi.svg")),
  hpp: svg(() => import("./hpp.svg")),
  hypr: svg(() => import("./hypr.svg")),
  ink: svg(() => import("./ink.svg")),
  karak: svg(() => import("./karak.svg")),
  katana: svg(() => import("./katana.svg")),
  kinto: svg(() => import("./kinto.svg")),
  kroma: svg(() => import("./kroma.svg")),
  lighter: svg(() => import("./lighter.svg")),
  linea: svg(() => import("./linea.svg")),
  lisk: svg(() => import("./lisk.svg")),
  mantle: svg(() => import("./mantle.svg")),
  metal: svg(() => import("./metal.svg")),
  metamail: svg(() => import("./metamail.svg")),
  metis: svg(() => import("./metis.svg")),
  mint: svg(() => import("./mint.svg")),
  mode: svg(() => import("./mode.svg")),
  morph: svg(() => import("./morph.svg")),
  nal: svg(() => import("./nal.svg")),
  nanonnetwork: svg(() => import("./nanonnetwork.svg")),
  opbnb: svg(() => import("./opbnb.svg")),
  optimism: svg(() => import("./optimism.svg")),
  optopia: svg(() => import("./optopia.svg")),
  paradex: svg(() => import("./paradex.svg")),
  parallel: svg(() => import("./parallel.svg")),
  pgn: svg(() => import("./pgn.svg")),
  phala: svg(() => import("./phala.svg")),
  plume: svg(() => import("./plume.svg")),
  polynomial: svg(() => import("./polynomial.svg")),
  powerloom: svg(() => import("./powerloom.svg")),
  r0ar: svg(() => import("./r0ar.svg")),
  race: svg(() => import("./race.svg")),
  rari: svg(() => import("./rari.svg")),
  river: svg(() => import("./river.svg")),
  scroll: svg(() => import("./scroll.svg")),
  settlus: svg(() => import("./settlus.svg")),
  shape: svg(() => import("./shape.svg")),
  snaxchain: svg(() => import("./snaxchain.svg")),
  soneium: svg(() => import("./soneium.svg")),
  spire: svg(() => import("./spire.svg")),
  starknet: svg(() => import("./starknet.svg")),
  superlumio: svg(() => import("./superlumio.svg")),
  superseed: svg(() => import("./superseed.svg")),
  swanchain: svg(() => import("./swanchain.svg")),
  swellchain: svg(() => import("./swellchain.svg")),
  symbiosis: svg(() => import("./symbiosis.svg")),
  taiko: svg(() => import("./taiko.svg")),
  thebinaryholdings: svg(() => import("./thebinaryholdings.svg")),
  unichain: svg(() => import("./unichain.svg")),
  world: svg(() => import("./world.svg")),
  xga: svg(() => import("./xga.svg")),
  zeronetwork: svg(() => import("./zeronetwork.svg")),
  zircuit: svg(() => import("./zircuit.svg")),
  zksync: svg(() => import("./zksync.svg")),
  zora: svg(() => import("./zora.svg")),

  // Image-based rollups
  infinaeon: "/rollups/infinaeon.png",
  lachain: "/rollups/lachain.jpg",
  lambda: "/rollups/lambda.png",
  manta: "/rollups/manta.png",
  orderly: "/rollups/orderly.png",
  pandasea: "/rollups/pandasea.png",
};
