name: "Set up DB"
description: "Set up the database for the CI environment"
runs:
  using: "composite"
  steps:
    - name: "Create .env file with db connection"
      uses: "SpicyPizza/create-envfile@v2.0"
      with:
        envkey_DATABASE_URL: "postgresql://blobscan:s3cr3t@localhost:5432/blobscan_dev?schema=public"
        envkey_DIRECT_URL: "postgresql://blobscan:s3cr3t@localhost:5432/blobscan_dev?schema=public"
    - name: "Apply Prisma migrations to db"
      shell: bash
      run: pnpm prisma migrate deploy --schema packages/db/prisma/schema.prisma
