# Dagster image with webserver, postgres, docker and k8s support.
# Used to run both dagster-webserver and the dagster-daemon.
FROM python:3.14-slim

ENV DAGSTER_HOME=/opt/dagster/dagster_home/

RUN pip install \
    dagster \
    dagster-webserver \
    dagster-postgres \
    dagster-docker \
    dagster-k8s

RUN mkdir -p $DAGSTER_HOME

COPY dagster.yaml workspace.yaml $DAGSTER_HOME

WORKDIR $DAGSTER_HOME
