import type { AppProps } from "next/app";
import { Button, ChakraProvider, Container } from "@chakra-ui/react";
import { extendTheme, type ThemeConfig } from "@chakra-ui/react";
import "@fontsource/lato/700.css";
import Head from "next/head";
import { Wagmi } from "../providers/Wagmi";
import { Superfluid } from "../providers/Superfluid";

// 2. Extend the theme to include custom colors, fonts, etc
const colors = {
  brand: {
    900: "#502eb4",
  },
};

const config: ThemeConfig = {
  initialColorMode: "light",
  useSystemColorMode: false,
};

const fonts = {
  heading: "Lato",
  body: "Lato",
};

const theme = extendTheme({ colors, config, fonts });

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <Wagmi>
      <Superfluid>
        <ChakraProvider theme={theme}>
          <Head>
            <title>Blobscan</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <Component {...pageProps} />
        </ChakraProvider>
      </Superfluid>
    </Wagmi>
  );
}

export default MyApp;
