import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Blobscan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to blobscan</h1>
        <Link href={`/block/${123456}`}>Take me there!</Link>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
