name: Changesets

on:
  workflow_run:
    workflows: ["CI"]
    branches: ["main"]
    types:
      - completed

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  DATABASE_URL: "postgresql://blobscan:s3cr3t@localhost:5432/blobscan_dev?schema=public"
  DIRECT_URL: "postgresql://blobscan:s3cr3t@localhost:5432/blobscan_dev?schema=public"

jobs:
  changesets:
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: blobscan_dev
          POSTGRES_USER: blobscan
          POSTGRES_PASSWORD: s3cr3t
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Create pull request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host

      - name: Setup
        uses: ./tooling/github/setup

      - name: Setup DB
        uses: ./tooling/github/setup-db

      - name: Create version pull request
        id: changesets
        uses: changesets/action@v1
        with:
          title: "chore: version packages"
          commit: "chore: version packages"
          version: pnpm changeset:version
          publish: pnpm changeset:release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
