name: Deployment

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
  push:
    branches:
      - next
      - master

jobs:
  deploy:
    name: Run remote deploy script
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@v0.0.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: deploy
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: ./deploy-blobscan.sh
