name: Deployment

on:
  push:
    branches: ["master", "next"]

jobs:
  deploy:
    if: github.ref_name == 'next'
    name: Run remote deploy script (staging)
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: appleboy/ssh-action@v0.0.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: deploy
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: ./deploy-blobscan.sh
