name: Docker Docs

on:
  push:
    branches: ["main"]
    paths:
      - "apps/docs/**"
      - "Dockerfile.docs"
      - "docker-entrypoint.sh"

jobs:
  release_docs_docker:
    name: Build Docker image (Docs)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host

      - name: Setup
        uses: ./tooling/github/setup

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set Github ENV variables
        shell: bash
        run: |
          echo "BUILD_TIMESTAMP=$(date '+%F %H:%M:%S')" >> $GITHUB_ENV
          echo "GIT_COMMIT=$(git rev-parse HEAD)" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_BLOBSCAN_RELEASE=$(git describe --tags)" >> $GITHUB_ENV

      - name: Extract metadata (tags, labels) for Docker (Docs)
        id: meta_docs
        uses: docker/metadata-action@v5
        with:
          images: |
            blossomlabs/blobscan-docs
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Build and push (docs)
        uses: docker/build-push-action@v6.5.0
        with:
          context: .
          push: true
          target: docs
          tags: ${{ steps.meta_docs.outputs.tags }}
          labels: ${{ steps.meta_docs.outputs.labels }}
          build-args: |
            NEXT_PUBLIC_BLOBSCAN_RELEASE=${{ env.NEXT_PUBLIC_BLOBSCAN_RELEASE }}
            BUILD_TIMESTAMP=${{ env.BUILD_TIMESTAMP }}
            GIT_COMMIT=${{ env.GIT_COMMIT }}
