name: Publish docker image

on:
  workflow_dispatch:
  push:
    branches:
      - "next"
      - "master"
      - "docker-*"  # Use this tag to force generating a docker image
    tags:
      - "v*"

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: blossomlabs/blobscan
          tags: |
            type=ref,event=branch
            type=raw,value=latest,enable=${{ github.ref_name == 'next' }}
            type=raw,value=stable,enable=${{ github.ref_name == 'master' }}

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set Github ENV variables
        shell: bash
        run: |
          echo "BUILD_TIMESTAMP=$(date '+%F %H:%M:%S')" >> $GITHUB_ENV
          echo "GIT_COMMIT=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BUILD_TIMESTAMP=${{ env.BUILD_TIMESTAMP }}
            GIT_COMMIT=${{ env.GIT_COMMIT }}
